# Generated by Django 3.2.7 on 2021-09-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210919_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
