# Generated by Django 3.2.7 on 2022-01-21 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Quantity should be >= 0')]),
            preserve_default=False,
        ),
    ]
