# Generated by Django 3.2.7 on 2022-02-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='quantity',
        ),
    ]
